package blockchain.baby.model;

import lombok.Data;

/**
 * Reward type that an organisation can issue.
 * Contains name, code, description and fingerprint.
 * Where fingerprint is signature generated by private key of the issuing organisation.
 * fingerprint can be verified by the public key of the issuing organisation.
 */
@Data
public class RewardType {
    private String name;
    private String code;
    private String description;
    private String fingerprint;
}
